# -*- coding: utf-8 -*-
"""AVA3 - Computacao em Nuvem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CzdP6OuT8sxcQRp4ORjn7sj-4rSbeNSg
"""

from flask import Flask, request, render_template
import pandas as pd


app = Flask(__name__)

data =  {
          'id': [1,2,3],
          'categoria': ['eletronico','eletronico','lampadas'],
          'nome': ['E-letro','Prefeitura de Rolandia','Supermercado Musamar'],
           'endereco': ['Rua Ermelindo Leão','Rua Cambe','Rua Pernambuco'],
           'numero': ['385','0','784'],
           'telefone': ['(43) 3339-0475','','(43) 3324-0020'],
           'cidade': ['Londrina','Rolandia','Londrina']
        }
df=pd.DataFrame(data)


@app.route('/busca', methods=['GET'])
def busca():
    op_categoria2 = str(request.args.get('opcao'))
    ndf=df.loc[df['categoria']== op_categoria2]
    return ndf.to_html()


@app.route('/sugerir')
def sugerir():
    return render_template("sugerir.html")

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)